import type { Metadata } from "next";
import localFont from "next/font/local";

import "@/shared/styles/globals.css";
import { Providers } from "./common/providers/Providers";
import AuthModal from "@/shared/components/composites/auth/AuthModal";

export const metadata: Metadata = {
  title: "Salon Flow",
  description: "Generated by create next app",
};

const ravi = localFont({
  src: [
    {
      path: "../shared/assets/fonts/ravi_normal.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../shared/assets/fonts/ravi_bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../shared/assets/fonts/ravi_medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../shared/assets/fonts/ravi_semibold.woff",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-ravi",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir={"rtl"} className={`${ravi.variable} font-sans`}>
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}

                    <AuthModal />
                    
        </Providers>
      </body>
    </html>
  );
}
